version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - mkdir -p ./lib/python/
      - PIP_TARGET="./lib/python/" pipenv install --dev --skip-lock
      - pipenv install awscli aws-sam-cli --skip-lock
      - pytest tests/
      - pipenv run sam package --template-file template.yaml --s3-bucket ${BUCKET_NAME} --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml

